import joi from "joi";

export const email = joi.string().email({minDomainSegments: 2, tlds: {allow: ['com']}}).required()
export const password = joi.string().min(6).max(30).required()
export const nameProduct = joi.string().required()
export const detailProduct = joi.string().required()
export const priceProduct = joi.number().required()
export const categoryProduct = joi.string().required()
export const reviewProduct = joi.string().required()
export const tagProduct = joi.string().required()
export const amountProduct = joi.number().required()
export const weightProduct = joi.number().required()
export const widthProduct = joi.number().required()
export const avatarProduct = joi.string().required()
export const detailImgProduct = joi.string().required()